import { GlobalConfig } from 'payload'

export const MenuSettingsGlobal: GlobalConfig = {
  slug: 'menu-settings',
  label: 'Menu Settings',
  admin: {
    group: 'Settings',
  },
  access: {
    read: () => true,
    update: ({ req }) => req.user?.role === 'superadmin',
  },
  fields: [
    {
      name: 'roleMenus',
      type: 'array',
      label: 'Role Menu Configuration',
      labels: {
        singular: 'Role Configuration',
        plural: 'Role Configurations',
      },
      fields: [
        {
          name: 'role',
          type: 'select',
          required: true,
          options: [
            { label: 'Admin', value: 'admin' },
            { label: 'Manager', value: 'manager' },
            { label: 'Account', value: 'account' },
            { label: 'Delivery', value: 'delivery' },
            { label: 'Branch', value: 'branch' },
            { label: 'Company', value: 'company' },
            { label: 'Factory', value: 'factory' },
            { label: 'Kitchen', value: 'kitchen' },
            { label: 'Chef', value: 'chef' },
            { label: 'Cashier', value: 'cashier' },
            { label: 'Waiter', value: 'waiter' },
            { label: 'Supervisor', value: 'supervisor' },
            { label: 'Driver', value: 'driver' },
            { label: 'Store Keeper', value: 'store_keeper' },
          ],
        },
        {
          name: 'visibleCollections',
          type: 'select',
          hasMany: true,
          label: 'Visible Collections',
          options: [
            { label: 'Users', value: 'users' },
            { label: 'Companies', value: 'companies' },
            { label: 'Branches', value: 'branches' },
            { label: 'Departments', value: 'departments' },
            { label: 'Categories', value: 'categories' },
            { label: 'Products', value: 'products' },
            { label: 'Raw Material Categories', value: 'raw-material-categories' },
            { label: 'Raw Materials', value: 'raw-materials' },
            { label: 'Raw Material Dealers', value: 'raw-material-dealers' },
            { label: 'Media', value: 'media' },
            { label: 'Dealers', value: 'dealers' },
            { label: 'Employees', value: 'employees' },
            { label: 'Message Threads', value: 'message-threads' },
            { label: 'Message Attachments', value: 'message-attachments' },
            { label: 'Messages', value: 'messages' },
            { label: 'Message Receipts', value: 'message-receipts' },
            { label: 'Billings', value: 'billings' },
            { label: 'Return Order', value: 'return-order' },
            { label: 'Closing Entries', value: 'closing-entries' },
            { label: 'Expenses', value: 'expenses' },
            { label: 'Stock Orders', value: 'stock-orders' },
            { label: 'Dealer Billings', value: 'dealer-billings' },
            { label: 'Raw Material Billings', value: 'raw-material-billings' },
            { label: 'Reviews', value: 'reviews' },
            { label: 'Customers', value: 'customers' },
            { label: 'Billing Customers', value: 'billing-customers' },
            { label: 'Instock Entries', value: 'instock-entries' },
            { label: 'Tables', value: 'tables' },
            { label: 'Kitchens', value: 'kitchens' },
            { label: 'Attendance', value: 'attendance' },
            { label: 'APK Files', value: 'apk-files' },
            { label: 'Stock Alerts', value: 'stock-alerts' },
            { label: 'Idempotency Keys', value: 'idempotency-keys' },
            { label: 'Waiter Calls', value: 'waiter-calls' },
          ],
        },
        {
          name: 'visibleGlobals',
          type: 'select',
          hasMany: true,
          label: 'Visible Globals',
          options: [
            { label: 'IP Settings', value: 'ip-settings' },
            { label: 'Jarvis', value: 'jarvis' },
            { label: 'Overall (Dashboard)', value: 'general-dashboard' },
            { label: 'Time Wise Report', value: 'time-wise-report' },
            { label: 'Branch Billing Report', value: 'branch-billing-report' },
            { label: 'GST Report', value: 'gst-report' },
            { label: 'All Bills Report', value: 'accounts-bills-report' },
            { label: 'Bill Summary', value: 'bill-summary' },
            { label: 'Category Wise Report', value: 'category-wise-report' },
            { label: 'Product Wise Report', value: 'product-wise-report' },
            { label: 'Product Time Report', value: 'product-time-report' },
            { label: 'Chef Report', value: 'chef-report' },
            { label: 'Closing Entry Report', value: 'closing-entry-report' },
            { label: 'Waiter Wise Billing Report', value: 'waiter-wise-billing-report' },
            { label: 'Inventory Report', value: 'inventory-report' },
            { label: 'Stock Order Report', value: 'stock-order-report' },
            { label: 'Afterstock Customer Report', value: 'afterstock-customer-report' },
            { label: 'Review Report', value: 'review-report' },
            { label: 'Instock Entry Report', value: 'instock-entry-report' },
            { label: 'Expense Report', value: 'expense-report' },
            { label: 'Return Order Report', value: 'return-order-report' },
            { label: 'Dealer Report', value: 'dealer-report' },
            { label: 'Raw Material Billing Report', value: 'raw-material-billing-report' },
            { label: 'Branch Geo Settings', value: 'branch-geo-settings' },
            { label: 'Network Status', value: 'network-status' },
            { label: 'Widget Settings', value: 'widget-settings' },
            { label: 'Customer Offer Settings', value: 'customer-offer-settings' },
            { label: 'App Download Settings', value: 'app-download-settings' },
            { label: 'App Version Settings', value: 'app-version-settings' },
          ],
        },
      ],
    },
  ],
}
